### ISSUE TITLE
Downloading Apex is broke

### ISSUE THREAD

**Issue by wispborne** [wispborne/TriOS#30]
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #4   package:trios/trios/download_manager/download_manager.dart 54:20  TriOSDownloadManager.addDownload.<fn>.<fn>
flutter: │ #5   package:flutter/src/foundation/change_notifier.dart 433:24        ChangeNotifier.notifyListeners
flutter: │ #6   package:flutter/src/foundation/change_notifier.dart 555:5         ValueNotifier.value=
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 22:12:54.136 (+0:07:58.159114)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ Download failed: https://github.com/theDragn/ApexDesignCollective/releases/latest/
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot rename file to 'C:\Users\whitm\AppData\Local\Temp\4a76b87e\', path = 'C:\Users\whitm\AppData\Local\Temp\4a76b87e\.partial' (OS Error: Access is denied.

, errno = 5)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.rename.<anonymous closure> (dart:io/file_impl.dart:335:7)
<asynchronous suspension>
#2      DownloadManager.download (package:trios/trios/download_manager/downloader.dart:107:11)
<asynchronous suspension>

**Comment by wispborne** [comment]
Fixed in v53
